In [ ]:


import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)
from imblearn.over_sampling import SMOTE

df = pd.read_csv("csv_result-ebay_confianca_completo.csv")



#Verificar valores ausentes


#Caso existam valores nulos:
df = df.dropna()

# 4. Transformar variáveis categóricas em numéricas
# No seu conjunto de dados existem:

# blacklist
# reputation

# como variáveis categóricas.

#Aplicando LabelEncoder
encoder_blacklist = LabelEncoder()
encoder_reputation = LabelEncoder()

df["blacklist"] = encoder_blacklist.fit_transform(df["blacklist"])

df["reputation"] = encoder_reputation.fit_transform(df["reputation"])

# 5. Separar Variáveis Explicativas e Alvo

X = df.drop("reputation", axis=1)

y = df["reputation"]
print('VALORES DE Y ORIGINAL')
print(np.unique(y, return_counts=True))
# 6. Dividir em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42,stratify=y)

print('VALORES DE Y DEPOIS DA DIVISÃO')
print(np.unique(y_train, return_counts=True))
# Utilizar SMOTE: OVERSAMPLING
smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

print('VALORES DE Y DEPOIS DO SMOTE')
print(np.unique(y_train_smote, return_counts=True))

# 7. Criar o modelo Random Forest
modelo = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)
# Parâmetros
# n_estimators=200 → quantidade de árvores
# random_state=42 → reproduzibilidade
# class_weight="balanced" → ajuda no desbalanceamento


# 8. Treinar o modelo
modelo.fit(X_train, y_train)

# 9. Fazer previsões
y_pred = modelo.predict(X_test)

# 10. Avaliar o modelo
# Acurácia
acuracia = accuracy_score(y_test, y_pred)



print("Acurácia:", acuracia)
# Matriz de Confusão
print('Matriz de Confusão:',confusion_matrix(y_test, y_pred))
# Relatório Completo
print(classification_report(y_test, y_pred))

#PARA CONHECIMENTO
#PARA FAZER O OVERSAMPLING
#OU SEJA 75% BONS 25% RUINS
#VER O DESBALANCEAMENTO NA VARIÁVEL TREINO




VALORES DE Y ORIGINAL
(array([0, 1]), array([4299, 1507]))
VALORES DE Y DEPOIS DA DIVISÃO
(array([0, 1]), array([3009, 1055]))
VALORES DE Y DEPOIS DO SMOTE
(array([0, 1]), array([3009, 3009]))
Acurácia: 0.7439724454649828
Matriz de Confusão: [[1283    7]
 [ 439   13]]
              precision    recall  f1-score   support

           0       0.75      0.99      0.85      1290
           1       0.65      0.03      0.06       452

    accuracy                           0.74      1742
   macro avg       0.70      0.51      0.45      1742
weighted avg       0.72      0.74      0.65      1742

